replicaCount: 1

image:
  repository: yormansjhr/go-web-app
  pullPolicy: IfNotPresent
  tag: "latest"

ingress:
  enabled: false
  className: ""
  annotations: {}

  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          